### Recuperar todas las peliculas
GET http://localhost:1234/api/movies

### Recuperar una pelicula por id
GET http://localhost:1234/api/movies/9e6106f0-848b-4810-a11a-3d832a5610f9

### Recuperar una pelicula por un genero
GET http://localhost:1234/api/movies?genre=action&title=avengers


### Crear una pelicula
POST http://localhost:1234/api/movies
Content-Type: application/json

{
  "title": "Napoleon",
  "year": 2023,
  "director": "SkivaDev",
  "duration": 156,
  "poster": "https://i.ebayimg.com/images/g/QFQAAOSwAQpfjaA6/s-l1200.jpg",
  "genre": ["Action", "Sci-Fi"]
}

### Actualizar una pelicula
PATCH http://localhost:1234/api/movies/9e6106f0-848b-4810-a11a-3d832a5610f9
Content-Type: application/json

{
  "title": "Fabrizio"
}