### Recuperar todas las peliculas
GET http://localhost:1234/api/movies

### Recuperar una pelicula por id
GET http://localhost:1234/api/movies/fb3327c5-1c81-11ef-ba55-50ebf6c4984e

### Recuperar una pelicula por un genero
GET http://localhost:1234/api/movies?genre=action&title=avengers


### Crear una pelicula
POST http://localhost:1234/api/movies
Content-Type: application/json

{
  "title": "Napoleon",
  "year": 2023,
  "director": "SkivaDev",
  "duration": 156,
  "poster": "https://i.ebayimg.com/images/g/QFQAAOSwAQpfjaA6/s-l1200.jpg",
  "genre": ["Action", "Sci-Fi"]
}

### Actualizar una pelicula
PATCH http://localhost:1234/api/movies/90b1cbb6-1c82-11ef-ba55-50ebf6c4984e
Content-Type: application/json

{
  "title": "Leonardo King Kong",
  "year": 2024,
  "genre": ["Horror"]
}

### Eliminar una pelicula
DELETE http://localhost:1234/api/movies/90b1c393-1c82-11ef-ba55-50ebf6c4984e